'use strict';
// Все баланс-параметры здесь. Правь числа — игра подхватит после перезагрузки.
const CFG = {
  world: { size: 6400, cell: 40, camp: { x: 480, y: 5900, r: 120 }, goal: { x: 5900, y: 520 } },
  time: { dayLen: 720, start: 7 },            // сек реального времени на игровые сутки
  player: {
    speed: 100, run: 1.6, sneak: 0.55, hp: 100, stam: 100, drain: 28, regen: 13,
    carry: 22, r: 9, vision: 280, visionNight: 190, pistolDmg: 30, fireCd: 0.32, spread: 0.06,
    boltRange: 380, hookRange: 340, foodRate: 0.14, radDecay: 0.25,
    noise: { run: 230, walk: 120, sneak: 45, shot: 750, bolt: 150 },
  },
  emission: { gapMin: 420, gapMax: 720, warn: 30, dur: 14, dps: 22, shelterR: 46, firstIn: 300 },
  counts: { anoms: 90, fields: 30, corpses: 50, bunkers: 14, radZones: 20, stashes: 80, rest: 10, labs: 3, roads: 2 },
  death: { moneyLoss: 0.4, hpOnRespawn: 60 },
  // Подземелье под каждым бункером: лабиринт из клеток cols×rows (тайл tile пикселей), шкафчики в тупиках, сейф в самой дальней точке.
  dungeon: { tile: 48, cols: 8, rows: 6, loops: 0.12, rooms: 2, lockers: 4, radSpots: 2, radRate: 1.4, base: 2,
    // Виды подземных врагов. w — вес появления по секторам 1–4; kind задаёт поведение (см. DEnemy в dungeon.js); drop — шанс трофея.
    enemies: {
      // Подземник: обычный преследователь, кусает, может вызвать кровотечение.
      crawler:  { name: 'Подземник', kind: 'crawl', spr: 'dweller', hp: 50, armor: 0, walk: 40, run: 105, dmg: 12, cd: 0.9, r: 9, sight: 230, xp: 14, bleed: 0.2, w: [4, 3, 2, 2] },
      // Кислотник: держится на расстоянии, после короткого замаха плюёт медленным сгустком (урон + замедление). Уворачивайся вбок или прячься за угол.
      spitter:  { name: 'Кислотник', kind: 'spit', spr: 'spitter', hp: 35, armor: 0, walk: 38, run: 85, dmg: 10, cd: 2.2, wind: 0.55, shot: 210, range: 260, keep: 110, r: 9, sight: 260, xp: 18, w: [0, 2, 3, 3],
                  drop: { id: 'glassgland', p: 0.4 } },
      // Тень: слепая, идёт на шум (бег слышно издалека, шаг — ближе, крадущегося почти не слышно), видна только вблизи. Горящую или раненую видно.
      shade:    { name: 'Тень', kind: 'shade', spr: 'shade', hp: 30, armor: 0, walk: 55, run: 150, dmg: 18, cd: 0.8, r: 8, sight: 0, hear: { run: 260, walk: 110, sneak: 45, idle: 25 }, xp: 20, w: [0, 1, 2, 3],
                  drop: { id: 'mistvial', p: 0.25 } },
      // Панцирник: медленный и бронированный. Заметив тебя в прямом коридоре, замирает (замах), потом несётся по прямой; врезавшись в стену, оглушён и получает на 50% больше урона.
      carapace: { name: 'Панцирник', kind: 'charge', spr: 'carapace', hp: 110, armor: 0.5, walk: 30, run: 62, dmg: 12, dash: 300, dashT: 1.1, reach: 300, dashDmg: 20, wind: 1.2, stun: 1.8, chargeCd: 4, cd: 1.4, r: 12, sight: 200, xp: 40, w: [0, 0, 1, 2],
                  drop: { id: 'plate', p: 0.7 } },
    } },

  anoms: {
    plesh: { snag: 0.9, shape: 'blob', rough: 0.22, sign: '#20180e', name: 'Комариная плешь', r: 32, dps: 75, w: [0, 0.6, 1.2, 2], col: '#a08a5a', react: 'Болт вдавило в землю, будто на него встал слон.',
      hint: 'Круглая проплешина. Земля голая, вокруг дохлые комары.', arts: ['stoneflower', 'nightstar', 'soul', 'ember'] },
    grinder: { snag: 0.85, shape: 'ring', hole: 0.42, sign: '#d8cfae', name: 'Мясорубка', r: 44, dps: 65, cycle: 5, act: 1.4, w: [0, 1, 2, 2], col: '#b07070', react: 'Болт перемололо в труху.',
      hint: 'Обрывки одежды и кости кольцом. Иногда слышен скрежет.', arts: ['stoneflower', 'thorn', 'soul', 'mirage'] },
    funnel: { snag: 0.6, shape: 'star', lobes: 3, sign: '#d8caa0', name: 'Воронка', r: 55, pull: 95, dps: 6, core: 0.35, coreDps: 45, w: [1, 2, 3, 3],
      col: '#9a8a66', react: 'Болт втянуло и разорвало.', hint: 'Пыль кружит по спирали, трава лежит по кругу.',
      arts: ['stoneflower', 'nightstar', 'moonlight', 'feather'] },
    electra: { snag: 0.7, shape: 'ellipse', asp: 1.6, sign: '#8fb0d8', name: 'Электра', r: 48, period: 5, charge: 1.3, dmg: 48, w: [2, 3, 2, 2],
      col: '#7fb8ff', react: 'Болт вспыхнул, воздух хлопнул.', hint: 'Воздух потрескивает, на камнях — нагар.',
      arts: ['medusa', 'soul', 'stoneflower'] },
    fluff: { snag: 0.9, shape: 'blob', rough: 0.3, sign: '#f4ecdc', name: 'Жгучий пух', r: 62, dps: 15, slow: 0.7, drift: 7, w: [3, 2, 1, 1],
      col: '#f0e8d8', react: 'Болт вспыхнул и осыпался пеплом.', hint: 'Белые хлопья висят в воздухе почти неподвижно.',
      arts: ['thorn', 'soul', 'medusa'] },
    slime: { snag: 0.75, shape: 'blob', asp: 1.25, rough: 0.2, sign: '#b8e8bc', name: 'Ведьмин студень', r: 54, slow: 0.3, dps: 3, w: [3, 2, 2, 1],
      col: '#9bd6a0', react: 'Болт увяз и медленно тонет.', hint: 'Блестящая плёнка на земле. Ни одной мухи.',
      arts: ['dud', 'medusa', 'thorn'] },
    spring: { snag: 0.85, shape: 'square', sign: '#e0c080', name: 'Пружина', r: 46, period: 6, charge: 1.1, dmg: 34, push: 190, w: [0, 2, 3, 2],
      col: '#d0a050', react: 'Болт подскочил и ушёл в небо.', hint: 'Земля пружинит под ногой. Трава примята кольцами.',
      arts: ['springheart', 'stoneflower', 'ember', 'feather'] },
    magnet: { snag: 0.35, shape: 'ellipse', asp: 1.3, sign: '#9aa0a8', name: 'Магнитная яма', r: 58, pull: 70, dps: 18, metalDps: 38, w: [0, 1, 2, 3],
      col: '#8aa0c0', react: 'Болт рванулся к центру и прилип.', hint: 'Ржавчина тянется к центру, железки лежат кольцом.',
      arts: ['lodestone', 'medusa', 'mirage'] },
    // Тлеющий колодец: между вспышками просто светится; вспышка — конус в сторону, куда «смотрит» колодец (видно по заряду). Поджигает.
    smolder: { snag: 0.85, shape: 'egg', sign: '#e0602a', name: 'Тлеющий колодец', r: 40, period: 5.5, charge: 1.1, dmg: 30, burn: 6, reach: 1.8, arc: 0.9, w: [0, 1, 2, 2],
      col: '#d06a3a', react: 'Болт вспыхнул и осыпался углями.', hint: 'Земля тлеет красным, тянет дымом. Вокруг ни травинки.',
      arts: ['glasstear', 'ashheart', 'ember', 'thorn'] },
  },

  arts: {
    medusa:      { name: 'Медуза',         val: 70,  w: 0.3, rad: 0.10, fx: { radRes: 0.12 },  desc: 'Слегка гасит радиацию.' },
    stoneflower: { name: 'Каменный цветок', val: 150, w: 0.4, rad: 0,    fx: { stamRegen: 7 },  desc: 'Быстрее восстанавливается дыхание.' },
    nightstar:   { name: 'Ночная звезда',  val: 210, w: 0.5, rad: 0.50, fx: { carry: 6 },      desc: 'Груз кажется легче. Фонит.' },
    soul:        { name: 'Душа',           val: 130, w: 0.3, rad: 0,    fx: { hpRegen: 1.2 },  desc: 'Раны затягиваются быстрее.' },
    thorn:       { name: 'Колючка',        val: 95,  w: 0.4, rad: 0.25, fx: { radRes: 0.30 },  desc: 'Сильно гасит радиацию, но сама фонит.' },
    moonlight:   { name: 'Лунный свет',    val: 340, w: 0.3, rad: 0.70, fx: { hpRegen: 2.6, lure: 1 }, sci: true, desc: 'Лечит. Притягивает мутантов.' },
    feather:     { name: 'Пёрышко',        val: 120, w: 0.1, rad: 0,    fx: { carry: 10, psy: 0.35 }, desc: 'Груз почти не чувствуется. Побочка: тревожит рассудок.' },
    mirage:      { name: 'Мираж',          val: 190, w: 0.3, rad: 0,    fx: { repel: 1, psy: 0.45 }, desc: 'Мутанты хуже замечают тебя. Побочка: видения.' },
    ember:       { name: 'Уголёк',         val: 170, w: 0.4, rad: 0.3,  fx: { stamRegen: 12 }, desc: 'Силы возвращаются быстро. Фонит.' },
    springheart: { name: 'Сердце пружины', val: 185, w: 0.4, rad: 0.1, fx: { stamRegen: 8, carry: 4 }, desc: 'Ноги легче, груз кажется меньше.' },
    lodestone:   { name: 'Магнитный камень', val: 210, w: 0.6, rad: 0.15, fx: { radRes: 0.2, stamRegen: 4 }, desc: 'Гасит радиацию. Стрелка компаса рядом с ним вертится.' },
    ashheart:    { name: 'Зола-сердце',    val: 230, w: 0.4, rad: 0.2, fx: { hpRegen: 0.8, fireRes: 0.35 }, desc: 'Раны затягиваются, огонь берёт слабее. Слегка фонит.' },
    glasstear:   { name: 'Стеклянная слеза', val: 110, w: 0.2, rad: 0, fx: { sight: 25 }, desc: 'Тёплая на ощупь. В темноте видно дальше.' },
    // Награда за цепочку «Нижний ярус»; в аномалиях не встречается
    echo:        { name: 'Эхо',           val: 280, w: 0.3, rad: 0.15, fx: { repel: 1, hpRegen: 1.0 }, desc: 'Зона шепчет тише. Мутанты хуже замечают тебя, раны затягиваются.' },
    dud:         { name: 'Пустышка',       val: 6,   w: 0.6, rad: 0,    fx: {},                desc: 'Красивая. Бесполезная.' },
  },

  items: {
    art:      { name: 'Артефакт', w: 0.3, val: 0, icon: '✦' },
    bolt:     { name: 'Болт',            w: 0.05, val: 1,  buy: 15, pack: 10,  icon: '⚙', desc: 'Бросай вперёд — проверяй путь.' },
    ammo:     { name: 'Патроны 9мм',     w: 0.02, val: 2,  buy: 12, pack: 6,   icon: '⁍' },
    medkit:   { name: 'Аптечка',         w: 0.3,  val: 25, buy: 45,  icon: '✚', use: { heal: 45, stopBleed: 1 } },
    food:     { name: 'Тушёнка',         w: 0.4,  val: 8,  buy: 14,  icon: '▤', use: { food: 40 } },
    antirad:  { name: 'Антирад',         w: 0.2,  val: 20, buy: 35,  icon: '⚗', use: { rad: -35 } },
    meat:     { name: 'Мясо мутанта',    w: 0.5,  val: 4,  icon: '🍖', use: { food: 15, rad: 6 } },
    earbone:    { name: 'Ушная косточка',   w: 0.2, val: 18, icon: '👂', part: true },
    glassgland: { name: 'Стеклянная железа', w: 0.2, val: 26, icon: '💧', part: true },
    plate:      { name: 'Ржавая пластина',  w: 0.6, val: 22, icon: '▰', part: true },
    quill:      { name: 'Игла щетинника',   w: 0.2, val: 24, icon: '↟', part: true },
    fang:       { name: 'Гнилой клык',      w: 0.2, val: 28, icon: '⌵', part: true },
    mistvial:   { name: 'Капля тумана',     w: 0.1, val: 45, icon: '⚗', part: true },
    gill:       { name: 'Жабра Топляка',    w: 0.2, val: 32, icon: '≋', part: true },
    coalfang:   { name: 'Угольный зуб',     w: 0.2, val: 30, icon: '⌵', part: true },
    canister:   { name: 'Канистра горючего', w: 0.8, val: 14, buy: 28, icon: '⛽', desc: 'Топливо для огнемёта. Хватает на 25 выдохов.' },
    firecoat:   { name: 'Огнеупорный плащ', w: 4, val: 110, buy: 260, icon: '🧥', desc: 'Ожог и вспышки колодцев −60%. Носится поверх костюма, места занимает много.' },
    headlamp: { name: 'Налобный фонарь', w: 0.5, val: 70, buy: 180, icon: '🔦', desc: 'Под землёй светлее (+80), а Тени различимы с большего расстояния. Работает, пока лежит в рюкзаке.' },
    // Снаряжение по слотам (характеристики и эффекты — Gear.BASE; из вещей одного вида работает лучшая в рюкзаке)
    hook:     { name: 'Крюк-кошка',          w: 0.4, val: 12,  buy: 35,  icon: '⚓', desc: 'Слот 9: брось за артефактом в аномалии — подтянет его к тебе без шага внутрь. Цепляется не всегда и не в любой момент; вернётся вместе с добычей.' },
    helmet:   { name: 'Каска',                w: 1,   val: 45,  buy: 110, icon: '⛑', desc: 'Радиация −10%, напряжение от Зоны −20%.' },
    helmet2:  { name: 'Противогаз',           w: 1.4, val: 120, buy: 300, icon: '🥽', desc: 'Радиация −25%, напряжение от Зоны −15%.' },
    boots:    { name: 'Ботинки бродяги',      w: 1.2, val: 55,  buy: 140, icon: '🥾', desc: 'Скорость +6%, шаги тише на 12%.' },
    pack:     { name: 'Разгрузка',            w: 1,   val: 50,  buy: 120, icon: '🎒', desc: 'Грузоподъёмность +5 кг.' },
    pack2:    { name: 'Туристический рюкзак', w: 1.8, val: 130, buy: 320, icon: '🧳', desc: 'Грузоподъёмность +9 кг.' },
    suit:     { name: 'Плащ сталкера',   w: 3,    val: 60, buy: 130, icon: '🧥', desc: 'Радиация −25%, аномалии −10%.' },
    scrap:    { name: 'Металлолом',     w: 0.5, val: 6,  icon: '🔩', junk: true },
    circuit:  { name: 'Плата',          w: 0.2, val: 15, icon: '▦',  junk: true },
    battery:  { name: 'Батарея',        w: 0.4, val: 11, icon: '🔋', junk: true },
    splint:     { name: 'Шина',           w: 0.3, val: 10,  buy: 30,  icon: '🩹', use: { fixFracture: 1 }, desc: 'Лечит перелом.' },
    antibiotic: { name: 'Антибиотик',     w: 0.1, val: 25,  buy: 55,  icon: '💊', use: { cureInfect: 1 }, desc: 'Лечит заражение раны.' },
    lure:       { name: 'Приманка',       w: 0.5, val: 6,   buy: 18,  icon: '🥩', desc: 'Слот 6: бросить. Хищники идут на запах, ты уходишь.' },
    sensor:     { name: 'Датчик движения', w: 0.6, val: 30,  buy: 70,  icon: '📟', use: { sensor: 1 }, desc: 'Ставится на землю, пищит при движении рядом.' },
    suit2:      { name: 'Комбинезон «Ветеран»', w: 6, val: 200, buy: 420, icon: '🥼', req: { carry: 2 }, desc: 'Радиация −45%, аномалии −25%. Нужен навык грузоподъёмности 2.' },
    detector2:  { name: 'Детектор-2',     w: 1.5, val: 300, buy: 650, icon: '📡', desc: 'Ещё дальше видны признаки аномалий.' },
    dogtag:     { name: 'Жетон экспедиции', w: 0.05, val: 15, icon: '🏷', desc: 'Тот, кого искали.' },
    repairkit:  { name: 'Ремкомплект',   w: 0.4, val: 15, buy: 40, icon: '🔧', use: { repairGun: 35 }, desc: 'Чинит 35% износа оружия.' },
    suitpatch:  { name: 'Заплатка костюма', w: 0.3, val: 12, buy: 35, icon: '🧵', use: { repairSuit: 35 }, desc: 'Чинит 35% износа костюма.' },
    reagent:    { name: 'Реагент опознания', w: 0.1, val: 30, icon: '🧪', use: { identify: 1 }, desc: 'Опознаёт один артефакт в рюкзаке.' },
    shock:      { name: 'Шок-бомба',    w: 0.5, val: 40, icon: '💥', desc: 'Слот 8: бросить. Разряд бьёт всех вокруг и оглушает.' },
    diary:      { name: 'Дневник экспедиции', w: 0.1, val: 20, icon: '📓', desc: 'Записи Штейна.' },
    detector: { name: 'Детектор аномалий', w: 1,  val: 90, buy: 220, icon: '📡', desc: 'Дальше видны признаки аномалий.' },
  },

  skills: {
    endurance: { name: 'Выносливость',   max: 5, desc: '+15% запас и восстановление сил' },
    carry:     { name: 'Грузоподъёмность', max: 5, desc: '+4 кг переносимого веса' },
    stealth:   { name: 'Скрытность',     max: 5, desc: 'Шум −15% за уровень' },
    sense:     { name: 'Чутьё аномалий', max: 5, desc: 'Дальше видны признаки; ПКМ называет тип' },
    trade:     { name: 'Торговля',       max: 5, desc: 'Покупка −4%, продажа +5%' },
    butcher:   { name: 'Разделка',       max: 5, desc: 'Больше добычи с туш' },
    mapping:   { name: 'Картография',      max: 5, desc: '+25% радиус разведки, дороже данные карты' },
    repair:    { name: 'Ремонт',           max: 5, desc: 'Ремонт дешевле на 12% за уровень' },
    lore:      { name: 'Знание артефактов', max: 5, desc: 'Неопознанные артефакты подсказывают свойства' },
    resist:    { name: 'Стойкость',      max: 5, desc: 'Радиация и стресс −5% за уровень' },
  },

  biomes: {
    meadow:     { name: 'Луг', patch: 'rgba(70,100,45,.30)', map: '#34492b', w: [4, 3, 1, 1],
      props: { tree: 0.3, bush: 0.6, tuft: 1.3, rock: 0.12, boulder: 0.04, deadtree: 0.05, hay: 0.05, well: 0.01 }, grass: 0.3,
      am: { fluff: 1.2, slime: 0.5, funnel: 0.6, electra: 0.7, plesh: 0.5, grinder: 0.2, spring: 0.5, magnet: 0.1, smolder: 0.2 } },
    forest:     { name: 'Лес', patch: 'rgba(30,70,40,.38)', map: '#1f3a24', w: [2, 3, 2, 1],
      props: { pine: 2.2, tree: 1.0, bush: 0.9, deadtree: 0.35, tuft: 0.9, rock: 0.1, bones: 0.04 }, grass: 0.2,
      am: { fluff: 1, slime: 1, funnel: 0.8, electra: 0.5, plesh: 1, grinder: 0.3, spring: 0.4, magnet: 0.2, smolder: 0.5 } },
    town:       { name: 'Хармонт (руины)', patch: 'rgba(110,105,95,.28)', map: '#4a4a44', w: [1, 3, 3, 1],
      props: { house: 0.7, ruin: 0.45, wall: 0.5, fence: 0.5, barrel: 0.15, bones: 0.06, tuft: 0.3, billboard: 0.03 },
      roadProps: { car: 0.55, car_b: 0.4, bus: 0.06, lamp: 0.5, bones: 0.05, tires: 0.1, tuft: 0.2 },
      am: { electra: 1.5, grinder: 1.6, plesh: 1, funnel: 0.8, fluff: 0.4, slime: 0.5, spring: 0.8, magnet: 1.4, smolder: 0.6 } },
    junkyard:   { name: 'Свалка техники', patch: 'rgba(120,70,40,.32)', map: '#5a3a28', w: [1, 3, 3, 2],
      props: { car: 1.0, car_b: 0.7, truck: 0.25, bus: 0.1, tires: 0.7, barrel: 0.6, container: 0.25, rock: 0.1, tuft: 0.2, pylon: 0.03 },
      am: { slime: 1.3, electra: 1.4, grinder: 1.6, plesh: 1, funnel: 0.6, fluff: 0.5, spring: 0.6, magnet: 2.4, smolder: 0.5 } },
    swamp:      { name: 'Болото', patch: 'rgba(50,90,90,.36)', map: '#254545', w: [1, 2, 2, 1], water: 0.4, grass: 0.35,
      props: { reed: 1.6, deadtree: 0.5, bush: 0.3, tuft: 0.4, bones: 0.05, tires: 0.05 },
      am: { slime: 2.5, fluff: 0.6, funnel: 0.4, electra: 0.6, plesh: 1, grinder: 0.1, spring: 0.3, magnet: 0.1, smolder: 0.05 } },
    industrial: { name: 'Заводская зона', patch: 'rgba(80,90,110,.34)', map: '#3c4452', w: [0, 1, 3, 4],
      props: { container: 0.5, tank: 0.35, pipe: 0.45, pylon: 0.35, wall: 0.4, house: 0.25, lamp: 0.2, barrel: 0.5, truck: 0.1, rail: 0.4, tower: 0.05 },
      am: { electra: 2.2, funnel: 1, grinder: 1.5, plesh: 1.2, slime: 0.5, fluff: 0.2, spring: 0.9, magnet: 2, smolder: 0.8 } },
    quarry:     { name: 'Карьер', patch: 'rgba(140,120,80,.34)', map: '#5e5238', w: [0, 2, 3, 3],
      props: { boulder: 1.1, rock: 1.6, crater: 0.6, deadtree: 0.06, tower: 0.05, tires: 0.05, dtuft: 0.15 },
      am: { funnel: 2.2, grinder: 1.8, plesh: 1.4, electra: 0.6, fluff: 0.3, slime: 0.2, spring: 1.6, magnet: 1, smolder: 0.7 } },
    deadfield:  { name: 'Мёртвое поле', patch: 'rgba(120,100,50,.34)', map: '#4a4228', w: [0, 1, 3, 4], grass: 0.3,
      props: { deadtree: 0.7, bones: 0.2, crater: 0.25, dtuft: 0.9, grave: 0.15, rock: 0.1, pylon: 0.06, tower: 0.02 },
      am: { fluff: 2.2, plesh: 2, slime: 0.6, funnel: 1, electra: 1, grinder: 0.7, spring: 1.2, magnet: 0.6, smolder: 1.4 } },
    saltflat:   { name: 'Солончак', patch: 'rgba(200,200,180,.26)', map: '#6a6a5c', w: [0, 1, 3, 3], grass: 0.1,
      props: { crater: 0.4, bones: 0.25, dtuft: 0.5, rock: 0.5, boulder: 0.3, deadtree: 0.08, rail: 0.25, pylon: 0.1, tower: 0.05 },
      am: { spring: 2.2, magnet: 1.2, electra: 0.8, funnel: 1.2, plesh: 0.8, fluff: 0.5, slime: 0.1, grinder: 0.4, smolder: 0.3 } },
    // Озёрный край — большие озёра с камышом: вода замедляет, а в воде живёт Топляк
    lake:       { name: 'Озёрный край', patch: 'rgba(40,86,116,.46)', map: '#1f3a4c', w: [1, 2, 2, 1], water: 0.95, waterSize: 1.6, grass: 0.2,
      props: { reed: 2.2, deadtree: 0.3, bush: 0.4, tuft: 0.5, bones: 0.08, tires: 0.05, rock: 0.1 },
      am: { slime: 1.6, fluff: 0.6, funnel: 0.4, electra: 0.9, plesh: 0.5, grinder: 0.1, spring: 0.3, magnet: 0.2, smolder: 0.02 } },
    // Гарь — выжженный лес: пепел, обугленные стволы, тлеющие колодцы. Ночью здесь охотится Углеглот.
    burnt:      { name: 'Гарь', patch: 'rgba(96,58,40,.62)', map: '#3c2b24', w: [0, 1, 3, 3],
      props: { burntree: 2.2, deadtree: 0.2, char: 1.6, ashpile: 1.1, rock: 0.1, bones: 0.12, crater: 0.15 },
      am: { smolder: 3.2, plesh: 1.2, funnel: 0.6, electra: 0.6, fluff: 0.8, slime: 0.05, grinder: 0.5, spring: 0.4, magnet: 0.3 } },
  },

  mut: {
    listener: { name: 'Слухач', hp: 40, walk: 55, run: 150, dmg: 9, cd: 0.8, r: 8, sight: 100, hear: 1.8, active: 'night', pack: [3, 5], count: 14, lunge: true, biomes: ['town', 'deadfield', 'forest'],
                prey: ['glass'], xp: 9, meat: 2, part: 'earbone', bleed: 0.35, roam: 350, dmin: 2, dmax: 4 },
    glass:    { name: 'Стеклоед', hp: 30, walk: 38, run: 125, dmg: 4, cd: 1.2, r: 9, sight: 170, hear: 1, active: 'day', pack: [4, 6], count: 9, biomes: ['meadow', 'forest', 'swamp'],
                timid: true, xp: 5, meat: 3, part: 'glassgland', roam: 250, dmin: 1, dmax: 3 },
    tin:      { name: 'Жестянка', hp: 120, armor: 0.5, walk: 40, run: 95, charge: 210, dmg: 24, cd: 1.5, r: 13, sight: 170, hear: 0.5, active: 'day',
                territory: 200, metal: true, fracture: 0.25, hostile: ['listener'], count: 14, biomes: ['junkyard', 'quarry', 'industrial', 'town'], xp: 24, meat: 4, part: 'plate', roam: 120, dmin: 1, dmax: 3 },
    fogger:   { name: 'Туманник', hp: 55, walk: 50, run: 135, dmg: 18, cd: 1, r: 8, sight: 210, hear: 0.8, active: 'weather', stalker: true,
                count: 9, biomes: ['swamp', 'deadfield', 'forest'], xp: 20, meat: 1, part: 'mistvial', roam: 300, dmin: 2, dmax: 4 },
    // Щетинник — днём охраняет участок леса и луга, бьёт с разбега иглами по бокам (кровотечение), гоняет стеклоедов.
    bristler: { name: 'Щетинник', hp: 100, armor: 0.2, walk: 45, run: 105, charge: 200, dmg: 17, cd: 1.3, r: 11, sight: 160, hear: 0.7, active: 'day',
                territory: 170, bleed: 0.5, hostile: ['glass'], count: 10, biomes: ['forest', 'meadow', 'swamp'], xp: 14, meat: 3, part: 'quill', roam: 130, dmin: 1, dmax: 3 },
    // Гнилозуб — ночная стая из болот и руин; укус заражает рану (нужен антибиотик).
    rotter:   { name: 'Гнилозуб', hp: 60, walk: 32, run: 88, dmg: 11, cd: 1.1, r: 9, sight: 130, hear: 1.2, active: 'night', pack: [2, 4], infect: 0.45,
                count: 8, biomes: ['swamp', 'deadfield', 'town'], xp: 15, meat: 2, part: 'fang', roam: 260, dmin: 2, dmax: 4 },
    // Топляк — живёт в воде озёр и болот. Лежит на дне, невидимый; кто подойдёт к воде ближе ~64 пикс — хватает и держит (нужно рваться или стрелять).
    // Из пруда не выходит: на берегу безопасно, кроме полосы у самой кромки.
    drowner:  { name: 'Топляк', hp: 65, armor: 0.1, walk: 28, run: 125, dmg: 9, cd: 1.2, r: 10, sight: 0, hear: 0, active: 'day', aquatic: true, wakeR: 64, grab: 1.8,
                count: 12, biomes: ['lake', 'swamp'], xp: 18, meat: 2, part: 'gill', roam: 0, dmin: 1, dmax: 4 },
    // Углеглот — ночной хищник Гари. Днём спит в золе (не виден, пока не подойдёшь на ~70 пикс), бросается из засады, огнеупорен.
    // Бегущий оставляет тлеющие угли, укус может поджечь.
    cinder:   { name: 'Углеглот', hp: 70, armor: 0.3, walk: 42, run: 118, dmg: 14, cd: 1.1, r: 10, sight: 150, hear: 1, active: 'night', ambush: true, wakeR: 70, hideR: 130,
                fireproof: true, trail: true, burn: 0.45, count: 7, biomes: ['burnt', 'deadfield', 'forest'], xp: 22, meat: 2, part: 'coalfang', roam: 220, dmin: 2, dmax: 4 },
  },


  weapons: {
    pistol:  { name: 'Пистолет', dmg: 30, cd: 0.32, spread: 0.15, pellets: 1, range: 320, noise: 750, price: 0,   wear: 0.175, repair: 0.6 },
    sawnoff: { name: 'Обрез',    dmg: 13, cd: 1.0,  spread: 0.32, pellets: 6, range: 220, noise: 900, price: 260, wear: 0.25,  repair: 0.7 },
    revolver: { lvl: 2, name: 'Револьвер', dmg: 44, cd: 0.5, spread: 0.09, pellets: 1, range: 420, noise: 850, price: 380, wear: 0.175, repair: 0.8 },
    rifle:   { lvl: 2, name: 'Винтовка', dmg: 64, cd: 0.85, spread: 0.05, pellets: 1, range: 680, noise: 950, price: 520, wear: 0.2,  repair: 1.0 },
    flamer:  { lvl: 3, name: 'Огнемёт-самоделка', dmg: 9, cd: 0.16, spread: 0, pellets: 1, range: 150, noise: 500, price: 540, wear: 0.15, repair: 1.0,
               cone: 0.42, pierce: true, ammo: 'canister', perAmmo: 25, note: 'конус, игнорирует броню, поджигает; топливо — канистры' },
    // Самострел — почти бесшумный (Тени и Слухачи не слышат), стреляет болтами; сильный выстрел, но медленный
    crossbow: { lvl: 2, name: 'Самострел', dmg: 34, cd: 1.1, spread: 0.05, pellets: 1, range: 420, noise: 60, price: 340, wear: 0.15, repair: 0.7, ammo: 'bolt', ambush: 2, note: 'бесшумный, стреляет болтами; по не заметившим — двойной урон' },
    smg:     { lvl: 3, name: 'ПП «Оса»', dmg: 15, cd: 0.14, spread: 0.2, pellets: 1, range: 330, noise: 1000, price: 620, wear: 0.14, repair: 1.1 },
  },
  // Ближний бой (Melee): dmg — урон удара, cd — перезарядка, reach — длина, arc — сектор (рад), noise — шум, back — множитель по не заметившим, lvl — уровень Мастерской для продажи
  melee: {
    knife:   { name: 'Нож', icon: '🔪', dmg: 16, cd: 0.45, reach: 36, arc: 1.1, noise: 70, back: 2.5, price: 0, note: 'Быстрый и почти бесшумный. По не заметившим — удар в спину ×2.5.' },
    shiv:    { name: 'Заточка', icon: '🗡', dmg: 11, cd: 0.28, reach: 30, arc: 0.9, noise: 35, back: 3.5, price: 70, note: 'Очень быстрая и тихая. Удар в спину ×3.5 — для тех, кто подкрадывается.' },
    machete: { name: 'Мачете', icon: '⚔', lvl: 2, dmg: 27, cd: 0.62, reach: 44, arc: 1.5, noise: 110, back: 2, price: 190, note: 'Широкий замах: задевает сразу нескольких.' },
    hatchet: { name: 'Топорик', icon: '🪓', lvl: 3, dmg: 38, cd: 0.95, reach: 40, arc: 1.2, noise: 140, back: 2, pierce: true, price: 340, note: 'Медленный, но тяжёлый: пробивает броню Панцирника и Жестянки.' },
  },
  gate: { rep: 15 },
  stalkers: {
    loner:   { name: 'Одиночка', hp: 60, walk: 55, run: 100, sight: 240, roam: 350, hostile: false, dmg: 8, acc: 0.45, range: 170, cd: 1.3, count: 5, dmin: 1, dmax: 3 },
    bandit:  { name: 'Бандит', hp: 70, walk: 60, run: 115, sight: 230, roam: 260, hostile: true, dmg: 10, acc: 0.4, range: 190, cd: 1.1, count: 5, dmin: 2, dmax: 4 },
    patrol:  { name: 'Оцепление', hp: 95, walk: 70, run: 130, sight: 360, roam: 0, hostile: true, dmg: 13, acc: 0.6, range: 210, cd: 0.9, count: 0, dmin: 4, dmax: 4 },
    wounded: { name: 'Раненый', hp: 40, walk: 0, run: 0, sight: 0, roam: 0, hostile: false, dmg: 0, acc: 0, range: 0, cd: 1, count: 4, dmin: 2, dmax: 3 },
  },
  events: [
    { k: 'medkit', mul: 1.5, text: 'Дефицит аптечек — дорожают.' },
    { k: 'junk', mul: 1.4, text: 'Скупщик набивает цену на хлам.' },
    { k: 'part', mul: 1.5, text: 'Учёные скупают трофеи мутантов.' },
    { k: 'art', mul: 0.8, text: 'Рынок артефактов просел.' },
    { k: 'ammo', mul: 1.4, text: 'Патроны на вес золота.' },
    { k: 'art', mul: 1.25, text: 'Заказчик ищет артефакты — цены растут.' },
    { k: 'bolt', mul: 0.7, text: 'Партия болтов и гаек — дёшево.' },
  ],
  lore: [
    'Визит длился сутки. Никто не помнит, кто первым сказал слово «Визит».',
    'Артефакты — не оружие и не подарки. Скорее то, что остаётся на месте пикника: пустые банки, обёртки, забытая вещь.',
    'Аномалии не охраняют артефакты. Артефакты просто лежат там, где Зона что-то уронила.',
    'Мутанты не злые. Они голодны и боятся, как мы. Зона для них — дом.',
    'Выброс — не буря. Скорее Зона переворачивается во сне.',
    'Одна экспедиция вернулась молча. Все кивали и смотрели в одну сторону — на северо-восток.',
    'Учёные сходятся в одном: Зона не пытается с нами говорить. Мы просто оказались рядом.',
    'Говорят, в центре лежит то, что исполняет самое заветное желание. Заветное — то, которое боишься назвать самому себе.',
    'Пустышки — не брак. Для «гостей» это был мусор. Мы копим их в шкафах.',
    'Кто долго ходит по Зоне, слышит её ритм: пять секунд тишины — хлопок, гул — затишье.',
    'Дети сталкеров рождаются иными. Никто не говорит вслух, что это значит.',
    'Всё, что человек выносит из Зоны, немного уносит и его самого. Возвращается не тот, кто ушёл.',
  ],
  endings: {
    greed:      { title: 'Золотой год', text: 'Ты сказал шару: «Хочу денег». Деньги пришли, но кто-то платит по счетам, которых ты не видел. Ты богат и больше не выходишь из дома. Зона осталась позади, но по ночам стучит в окно.' },
    cruelty:    { title: 'Хозяин пустоши', text: 'Ты пришёл к шару с чёрной душой. Он не ответил. Ты вернулся — лагерь пуст, люди ушли. Ты сильнее всех и совсем один.' },
    mercy:      { title: 'Счастье для всех, даром', text: 'Ты не просил ничего для себя. «Счастья для всех, даром, и пусть никто не уйдёт обиженным». Шар молчал долго. Потом Зона выдохнула. В лагере тихо горит костёр.' },
    understand: { title: 'Гость', text: 'Ты не просил. Ты слушал. Зона не отвечала словами — показала себя, как ребёнок показывает игрушку. Она не враг и не друг. Ты записал всё и вернулся. Первым.' },
    silence:    { title: 'Пустой вопрос', text: 'Ты дошёл. Постоял. Шар не отозвался. Ты повернул домой и понял, что вопрос был не у шара, а у тебя. Дорога назад пустая и длинная.' },
  },

  buildings: {
    buyer:    { name: 'Скупка', ups: [{ money: 250, mat: { scrap: 6, circuit: 2 } }, { money: 600, mat: { scrap: 12, circuit: 4, battery: 3 } }],
      fx: ['Базовые цены скупки.', 'Цены скупки и учёного +8%. Весы точнее, вывеска ярче.', 'Цены +16%. Появился оптовый заказчик.'] },
    gun:      { name: 'Мастерская', ups: [{ money: 300, mat: { scrap: 8, circuit: 2 } }, { money: 700, mat: { scrap: 14, circuit: 5, battery: 3 } }],
      fx: ['Ремонт по базовой цене. Верстак: болты, шины.', 'Ремонт −25%. Открыта винтовка. Верстак: приманки, датчики.', 'Ремонт −50%. Верстак: аптечки, антирад.'] },
    gear:     { name: 'Снабжение', ups: [{ money: 300, mat: { scrap: 6, battery: 2 } }, { money: 650, mat: { scrap: 10, circuit: 4, battery: 4 } }],
      fx: ['Базовый ассортимент: еда, аптечки, шины, болты.', 'Скидка 5%. В продаже костюм, детектор, датчики.', 'Скидка 10%. В продаже «Ветеран» и Детектор-2.'] },
    sci:      { name: 'Лаборатория', ups: [{ money: 350, mat: { circuit: 4, battery: 2 } }, { money: 800, mat: { circuit: 8, battery: 4, scrap: 6 } }],
      fx: ['Опознание 20 ₽, исследование 40 ₽.', 'Опознание 10 ₽, исследование 25 ₽.', 'Опознание бесплатно, исследование 10 ₽.'] },
    bar:      { name: 'Бар', ups: [{ money: 250, mat: { scrap: 6, battery: 1 } }, { money: 600, mat: { scrap: 10, circuit: 3, battery: 3 } }],
      fx: ['Три-четыре задания.', 'Награды за задания +15%, ещё одно предложение.', 'Награды +30%, два дополнительных задания.'] },
    barracks: { name: 'Казарма', ups: [{ money: 200, mat: { scrap: 8 } }, { money: 500, mat: { scrap: 12, battery: 3 } }],
      fx: ['Койка 15 ₽.', 'Койка 8 ₽. Лечит инфекцию и переломы.', 'Койка бесплатно. Ещё сытость и −40 радиации.'] },
    storage:  { name: 'Склад', ups: [{ money: 200, mat: { scrap: 6 } }, { money: 500, mat: { scrap: 10, circuit: 3 } }],
      fx: ['24 ячейки.', '48 ячеек.', 'Без ограничения.'] },
  },
  // Ремонт из хлама и тюнинг. repair: сколько % износа закрывает 1 металлолом / 1 схема; cost[n] — цена (n+1)-го улучшения; максимум улучшений = уровень мастерской (оружие) или снабжения (костюм)
  tune: { repair: { scrap: 8, circuit: 35 }, cost: [{ scrap: 6, circuit: 3 }, { scrap: 10, circuit: 5, plate: 2 }, { scrap: 14, circuit: 7, plate: 3, battery: 2 }] },
  // Разборка на верстаке: что даёт вещь (костюмы — ×(1 + 0.3 за ступень редкости)); оружие считается по цене
  salvage: { hook: { scrap: 2 }, helmet: { scrap: 3 }, helmet2: { scrap: 4, circuit: 1 }, boots: { scrap: 3 }, pack: { scrap: 2 }, pack2: { scrap: 4, plate: 1 }, suit: { scrap: 4 }, suit2: { scrap: 6, plate: 2 }, firecoat: { scrap: 5, circuit: 1, battery: 1 }, detector: { circuit: 3, battery: 1, scrap: 1 }, detector2: { circuit: 5, battery: 2 }, headlamp: { circuit: 1, battery: 1 }, sensor: { circuit: 1, battery: 1 }, repairkit: { scrap: 2 } },
  // Награда растёт с глубиной пропорционально риску: множитель к деньгам и количеству добычи по сектору 1–4 (контейнеры, тела, сталкеры, бункеры)
  reward: { mul: [1, 1.7, 2.6, 3.6] },
  gearStock: { hook: 1, suit: 2, detector: 2, sensor: 2, suit2: 3, detector2: 3, firecoat: 3, headlamp: 2, helmet: 1, pack: 1, boots: 2, helmet2: 3, pack2: 3 },
  recipes: [
    { id: 'hook',     st: 'gun', name: 'Крюк-кошка',          lvl: 1, mat: { scrap: 3, circuit: 1 }, out: ['hook', 1] },
    { id: 'bolts',    st: 'gun', name: 'Болты ×10',           lvl: 1, mat: { scrap: 2 }, out: ['bolt', 10] },
    { id: 'splint',   st: 'gun', name: 'Шина',                lvl: 1, mat: { scrap: 2 }, out: ['splint', 1] },
    { id: 'repairkit', st: 'gun', name: 'Ремкомплект',        lvl: 1, mat: { scrap: 3, circuit: 1 }, out: ['repairkit', 1] },
    { id: 'suitpatch', st: 'gun', name: 'Заплатка костюма',   lvl: 1, mat: { scrap: 2, circuit: 1 }, out: ['suitpatch', 1] },
    { id: 'ammo',     st: 'gun', name: 'Патроны ×12',         lvl: 2, mat: { scrap: 2, battery: 1 }, out: ['ammo', 12] },
    { id: 'lure',     st: 'gun', name: 'Приманка',            lvl: 2, mat: { meat: 1, scrap: 1 }, out: ['lure', 1] },
    { id: 'sensor',   st: 'gun', name: 'Датчик движения',     lvl: 2, mat: { circuit: 2, battery: 1 }, out: ['sensor', 1] },
    { id: 'remelt',   st: 'gun', name: 'Переплавка: 3 пустышки → артефакт', lvl: 2, mat: { 'art:dud': 3 }, out: ['art', ['medusa', 'thorn', 'soul', 'stoneflower']] },
    { id: 'antirad2', st: 'sci', name: 'Антирад из жабр',   lvl: 1, mat: { gill: 2 }, out: ['antirad', 2] },
    { id: 'canister', st: 'gun', name: 'Канистра горючего',   lvl: 3, mat: { scrap: 3, meat: 2 }, out: ['canister', 1] },
    { id: 'shock',    st: 'gun', name: 'Шок-бомба',           lvl: 3, mat: { battery: 2, circuit: 1, scrap: 1 }, out: ['shock', 1] },
    { id: 'antirad',  st: 'gun', name: 'Антирад',             lvl: 3, mat: { battery: 1, circuit: 1, meat: 1 }, out: ['antirad', 1] },
    { id: 'medkit',   st: 'gun', name: 'Аптечка',             lvl: 3, mat: { circuit: 1, scrap: 2, battery: 1 }, out: ['medkit', 1] },
    { id: 'suit2',    st: 'gun', name: 'Комбинезон «Ветеран»', lvl: 3, mat: { suit: 1, plate: 3, scrap: 6 }, out: ['suit2', 1], req: { carry: 2 } },
    { id: 'reagent',  st: 'sci', name: 'Реагент опознания',   lvl: 1, mat: { glassgland: 1, battery: 1 }, out: ['reagent', 1] },
    { id: 'antibiotic', st: 'sci', name: 'Антибиотик',        lvl: 2, mat: { glassgland: 1, circuit: 1 }, out: ['antibiotic', 1] },
    { id: 'detector', st: 'sci', name: 'Детектор аномалий',   lvl: 2, mat: { circuit: 4, battery: 2, scrap: 3 }, out: ['detector', 1] },
    { id: 'detector2', st: 'sci', name: 'Детектор-2',         lvl: 3, mat: { detector: 1, circuit: 4, mistvial: 1 }, out: ['detector2', 1] },
  ],
  rooms: {
    bar:      { name: 'Бар «Обочина»', floor: '#4a3422', floor2: '#3f2c1d', wall: '#3a2a20' },
    buyer:    { name: 'Скупка «Борода»', floor: '#3e3a30', floor2: '#36322a', wall: '#4a4436' },
    gun:      { name: 'Мастерская', floor: '#3a3a3c', floor2: '#323234', wall: '#4a4a4e' },
    gear:     { name: 'Снабжение «Кум»', floor: '#2f3c4a', floor2: '#2a3642', wall: '#3a4c60' },
    sci:      { name: 'Лаборатория «Лис»', floor: '#4a5658', floor2: '#414c4e', wall: '#5a6a6c' },
    market:   { name: 'Торговый дом «Обочина»', floor: '#3a4038', floor2: '#333930', wall: '#48503f' },
    barracks: { name: 'Казарма', floor: '#3c3f2c', floor2: '#353826', wall: '#4a4e38' },
  },
  vendors: {
    buyer: { name: 'Скупщик «Борода»',   ang: 0.2,  col: '#c9a24a', buys: { art: 1, part: 1, meat: 1, junk: 1 }, likes: { battery: 1.3, circuit: 1.4 }, sells: [] },
    gun:   { name: 'Оружейник «Ржавый»', ang: 1.5,  col: '#a5a5a5', buys: { part: 0.8, junk: 1 }, likes: { plate: 2, earbone: 1.4, scrap: 1.6 }, sells: ['ammo', 'bolt', 'canister'] },
    gear:  { name: 'Снабженец «Кум»',    ang: 2.7,  col: '#7fa06a', buys: {}, sells: ['food', 'medkit', 'antirad', 'splint', 'antibiotic', 'hook', 'suit', 'suit2', 'firecoat', 'helmet', 'helmet2', 'boots', 'pack', 'pack2', 'headlamp', 'detector', 'detector2', 'lure', 'sensor', 'bolt'] },
    sci:   { name: 'Учёный «Лис»',       ang: 3.9,  col: '#7fb8ff', buys: { art: 1.25, part: 0.6 }, likes: { mistvial: 2.2, glassgland: 1.7, gill: 1.5 }, sells: [], ident: 20 },
    // Торговый дом — общий прилавок трёх бывших лавок (Скупка, Снабжение, Оружейная) и опознания Лаборатории: всё покупается, продаётся и опознаётся в одном здании.
    // Ассортимент — сумма Снабжения и Оружейной (Camp.stock), цена продажи — лучшая из Скупки, Лаборатории и Оружейной (sellPrice); уровни зданий прежние.
    market: { name: 'Торговый дом «Обочина»', ang: 0.9, col: '#c9a24a', buys: { art: 1, part: 1, meat: 1, junk: 1 }, likes: {}, sells: [], ident: 20 },
    bar:   { name: 'Бармен «Сидор»',     ang: 5.1,  col: '#d08a5a', buys: {}, sells: [], sleep: 15, map: 60, noteSell: 15 },
  },

  // Жители лагеря: с ними можно поговорить (E). id совпадает с Camp.build; topics — вопросы; k — вид ответа (см. Meta.talk).
  // story открывается один раз при репутации ≥ 3 и приоткрывает знание о Зоне.
  talk: {
    garik:  { role: 'болтун-сталкер', greet: 'Гарик щурится: «А, свежее лицо. Спрашивай — я в Зоне с первого дня, только с языка не слезаю».',
              topics: [{ k: 'rumor', t: 'Что слышно?', s: 'Слух' }, { k: 'tip', t: 'Как выжить в Зоне?', s: 'Совет бывалого' }, { k: 'story', t: 'Расскажи что-нибудь настоящее', s: 'Нужна репутация 3+' }],
              story: 'Ходили мы втроём к старой лаборатории за Солончаком. Вернулся один. Шкафы там целые — не потому что никто не дошёл, а потому что дошедшие не возвращались.' },
    mosol:  { role: 'коллекционер', greet: 'Мосол перебирает что-то в ладонях: «Пустышки. Красивые, правда? Тащи — не пожалеешь».',
              topics: [{ k: 'duds', t: 'Продать пустышки', s: '9 ₽ за штуку (Скупщик даёт 6)' }, { k: 'text', t: 'Зачем они тебе?', s: 'Разговор', a: 'Три пустышки в мастерской — одна настоящая штука. Я бы сам переплавлял, да руки не те. Ты — переплавляй. Мне остальное.' }, { k: 'story', t: 'Расскажи что-нибудь настоящее', s: 'Нужна репутация 3+' }],
              story: 'Пустышки — это не брак. Я нашёл одну в пепле, тёплую, будто её только что держали. Зона не роняет вещи просто так. Она их… оставляет.' },
    sedoy:  { role: 'старый сталкер', greet: 'Седой не отрывает взгляда от огня: «Молчи и слушай. Зона всё расскажет — если ты тихий».',
              topics: [{ k: 'emission', t: 'Скоро выброс?', s: 'Он чувствует зубами' }, { k: 'tip', t: 'Что бы ты сделал на моём месте?', s: 'Совет бывалого' }, { k: 'story', t: 'Расскажи что-нибудь настоящее', s: 'Нужна репутация 3+' }],
              story: 'Выброс — не буря. Скорее Зона переворачивается во сне. Я лежал в поле, когда она перевернулась. Проснулся — а карта другая. Карту-то мы и составляем, а она нас — никогда.' },
    guard1: { role: 'часовой', greet: 'Часовой не опускает винтовку: «Слушаю. Только быстро — у меня пост».',
              topics: [{ k: 'gate', t: 'Как пройти в сектор 4?', s: 'Оцепление и пропуск' }, { k: 'text', t: 'Что за воротами?', s: 'Разговор', a: 'Зона. Днём — жестянки и щетинники, ночью — слухачи, гнилозубы и то, что выползает из золы. Слушай вокруг, а не только под ноги.' }],
              story: 'Раньше здесь был просто блокпост: шлагбаум и два мешка песка. Потом кто-то принёс первый артефакт, и лагерь вырос вокруг него, как гриб.' },
    guard2: { role: 'часовой', greet: 'Второй часовой кивает: «Возвращайся целым. Мы тут не любим хоронить».',
              topics: [{ k: 'tip', t: 'Чем опасна Зона?', s: 'Совет бывалого' }, { k: 'text', t: 'Как идёт вахта?', s: 'Разговор', a: 'Ночью тихо, будто прислушивается. Днём — шум. Чем тише становится Зона, тем ближе выброс.' }, { k: 'story', t: 'Расскажи что-нибудь настоящее', s: 'Нужна репутация 3+' }],
              story: 'Под бункерами кто-то есть. Не мутанты — те лезут наверх. А эти сидят внизу и ждут. Спускаешься — слышишь: шепчут. Шепчут на звук твоих шагов.' },
    lyokha: { role: 'кладовщик', greet: 'Лёха хлопает по ящику: «Всё в целости. Не забывай: тяжёлым в Зону не ходят».',
              topics: [{ k: 'locker', t: 'Открыть ящик хранения', s: 'Твои вещи в безопасности' }, { k: 'text', t: 'Как устроен склад?', s: 'Разговор', a: 'Ящик держит вещи, пока ты жив и в лагере. Улучшишь склад — вместимость вырастет, а на третьем уровне лимита нет вовсе.' }, { k: 'story', t: 'Расскажи что-нибудь настоящее', s: 'Нужна репутация 3+' }],
              story: 'Один сталкер оставил у меня ящик и ушёл. Полгода не приходил. Я открыл: внутри только дневник и пустышка. Записка: «Если не вернусь, отдай Сидору». Я отдал.' },
  },
  // Записки экспедиции Штейна, найденные в сейфах трёх бункеров цепочки «Нижний ярус» (по порядку)
  deepNotes: [
    'Штейн, день 12: «Спустились в первый бункер. Внизу не пусто. Они не бросаются сразу — сначала слушают. Записываю: шёпот идёт на звук шагов. Красться. Идти дальше».',
    'Штейн, день 14: «Второй. Вика перестала говорить вслух, только слушает. Тени — не мутанты. Я нашёл жетон на одном из них. Жетон Пашки-Ржавого. Он умер прошлой зимой».',
    'Штейн, день 17: «Третий. Всё сходится. Они не мутировали — они остались. Те, кто спустился до нас и не вернулся, слушают Зону изнутри. Если ты это читаешь — не спускайся четвёртый раз».',
  ],
  // Советы бывалых: о механиках игры, общие для разговоров
  tips: [
    'Болты — глаза сталкера. Бросай перед собой: воздух хлопнет, потянется, вспыхнет — значит, там аномалия.',
    'Красться (Ctrl) вдвое сужает обзор слухачей и делает тебя почти невидимым для Тени. В темноте бункера это важнее патронов.',
    'Огонь берёт всё, кроме Углеглота. Огнемёт бьёт сквозь броню — Панцирника и Жестянку он любит.',
    'Пламя тушит вода и аптечка. Огнеупорный плащ снимает ожог на шестьдесят процентов, и колодец в Гари тебе не страшен.',
    'Кислотник плюёт медленно: сделай шаг вбок — и сгусток пролетит. Панцирник разгоняется по прямой: уйди с линии — и он сам врежется в стену.',
    'Перед выбросом Зона затихает. Слышишь сирену — бегом в лагерь или в бункер, внизу выброс не бьёт.',
    'Штейн ушёл под землю и не вернулся. Сидор говорит, в бункерах остались его записки — но для тех, кто уже читал дневник.',
    'Пустышки не выбрасывай: три штуки на верстаке — настоящий артефакт. Мосол за них даст побольше Скупщика.',
    'Неопознанный артефакт в контейнер не положишь. Отнеси к Учёному — 20 рублей, и знаешь, что держишь.',
    'Тяжёлым в Зону не ходят: перегруз режет скорость и шумит. Лишнее — в ящик у Лёхи.',
    'Записки на трупах — не только память. Иногда там помечена аномалия, которую лучше обойти.',
    'Сейфы в бункерах — самая жирная добыча, но и охраны там больше. Чем глубже сектор, тем хуже твари внизу.',
    'Заражение лечит только антибиотик или ночь в казарме второго уровня. Гнилозуб кусает — не тяни.',
  ],
  rumors: [
    'Слухачи слепые, но слышат каждый шаг. Иди тихо — пройдёшь мимо. Побежишь — позовёшь всю стаю.',
    'Электра «дышит»: пять секунд тишины, потом хлопок. Считай.',
    'Ночью выходят слухачи. Днём — жестянки. В туман — то, что стоит за спиной. Выбирай, с кем встретиться.',
    'Жестянка на разгоне не смотрит под ноги. Знающие люди водят её через аномалии.',
    'После выброса Зона тасуется. Старая карта — просто бумага.',
    'В бункерах во время выброса можно пересидеть. Найди их заранее.',
    'Говорят, в самом центре, на северо-востоке, что-то лежит. Никто не вернулся с описанием.',
    'Пустышки любят ставить рядом со студнем. Издевается Зона, не иначе.',
    'Лунный свет тянет тварей. Не носи его в ночь без нужды.',
    'Туманник стоит, пока на него смотришь. Отвернулся — он ближе. Целься в него, не пяться.',
    'Стеклоеды — как олени, только прозрачные. Слухачи их любят. Стадо побежало — значит, рядом кто-то.',
    'Плащ не спасёт, но дольше проживёшь. Детектор — дальше видишь признаки.',
    'Пружина сначала притихает, потом подбрасывает. Слышишь тишину под ногами — прыгай в сторону, не вперёд.',
    'Магнитная яма съедает железо. Жестянку туда заманишь — сама разберётся. Себе оставь только то, что не звенит.',
    'Щетинник днём стоит на своём участке. Иглы у него не для красоты — обходи стороной или бей с расстояния.',
    'В озёрах кто-то живёт. Идёшь вдоль воды — держись на шаг от кромки. Схватит — рвись вбок, а не стой.',
    'Гнилозуб кусает — рана гноится. Аптечка без антибиотика тут не помощница.',
    'В Гари днём кажется, что всё вымерло. Ночью из золы встаёт Углеглот. Смотри под ноги — там, где пепел свежий.',
    'Тлеющий колодец не бьёт наугад: он смотрит в одну сторону, светится и на секунду набирает воздух. Не стой в этой стороне.',
    'Вдоль Пепельного тракта стоят выгоревшие машины. Внутри кое-что осталось, но и у тракта есть хозяева.',
    'За Солончаком, говорят, стоят старые лаборатории: ограда, фон и «пружины» по кругу. Шкафы внутри так и не тронуты.',
  ],
  notes: [
    'Дошли до второго моста. Вася пошёл первым. Больше вопросов нет.',
    'Жестянка у камней территориальная. Звенит болт — приходит. Ест их, как семечки.',
    'Туман лёг. За спиной кто-то стоит. Оборачиваюсь — никого. Отхожу — он ближе. Не крути головой.',
    'Болты кончились. Пришлось идти по памяти. Память подвела.',
    'Пух всегда висит там, где нет ветра. Запомни: нет ветра — нет дороги.',
    'Если слышишь гул, а под ногами всё чисто — назад, шагом, не бегом.',
    'Выброс застал в поле. Лёг, закрыл голову. Живой. Не знаю зачем.',
    'Артефакт красивый, а продать не смог — Лис сказал: пустышка. Второй раз не куплюсь.',
  ],
};
